Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -136,12 +136,12 @@ jobs:
       
       - name: Copy run-latest.json File
         run: |
-            FILE_PATH=$(find /home/runner/work/SustainableLeverage/SustainableLeverage/broadcast/DeployContracts.s.sol -name 'run-latest.json')
-            if [ -z "$FILE_PATH" ]; then
-                echo "run-latest.json not found"
-                exit 1
-            fi
-            cp "$FILE_PATH" /home/runner/work/SustainableLeverage/deployments/1337-deployments.json
+          FILE_PATH=$(find /home/runner/work/SustainableLeverage/SustainableLeverage/broadcast/DeployContracts.s.sol -name 'run-latest.json')
+          if [ -z "$FILE_PATH" ]; then
+              echo "run-latest.json not found"
+              exit 1
+          fi
+          cp "$FILE_PATH" /home/runner/work/SustainableLeverage/deployments/1337-deployments.json
 
 
       - name: "Commit the deployment changes"
